version: '3'

services:
  app:
    container_name: react-typescript
    image: node:18-alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - json-server
    command: sh -c "npm install && npm run dev"
    ports:
      - '5173:5173'

  json-server:
    container_name: json-server
    image: node:18-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run server"
    ports:
      - '3001:3001'
